"""Auto-generated CU vocabulary catalog. Do not edit by hand — run scripts/build_vocab.py."""

from __future__ import annotations

from typing import Any

TAG_ROWS: list[dict[str, Any]] = [
    {
        "slug": "anime",
        "name": "Anime",
        "category": "anime",
        "keywords": ("anime", "manga", "waifu", "naruto", "onepiece", "アニメ", "アニメーション", "hoathinhnhat"),
        "aliases": (("hoathinhnhat", "vi"), ("ho\u1ea1t h\u00ecnh nh\u1eadt", "vi"),),
        "clip": ("anime illustration", "anime character art", "japanese animation"),
    },
    {
        "slug": "manga",
        "name": "Manga",
        "category": "anime",
        "keywords": ("manga", "manhwa", "manhua", "comic art"),
        "aliases": (("truy\u1ec7n tranh", "vi"),),
        "clip": ("manga comic art", "manga drawing"),
    },
    {
        "slug": "cosplay",
        "name": "Cosplay",
        "category": "cosplay",
        "keywords": ("cosplay", "cosplayer", "costumes"),
        "aliases": (),
        "clip": ("cosplay costume", "person in anime cosplay"),
    },
    {
        "slug": "music",
        "name": "Music",
        "category": "music",
        "keywords": ("music", "lyrics", "song", "amnhac", "nhac", "音楽", "nhạc", "baihat", "bài hát"),
        "aliases": (("amnhac", "vi"), ("\u00e2m nh\u1ea1c", "vi"),),
        "clip": ("music video", "person singing", "musical performance"),
    },
    {
        "slug": "lofi",
        "name": "Lofi",
        "category": "music",
        "keywords": ("lofi", "lo-fi", "chillhop", "chill beats"),
        "aliases": (("chill", "en"),),
        "clip": ("lofi aesthetic room", "chill study aesthetic"),
    },
    {
        "slug": "lyrics",
        "name": "Lyrics",
        "category": "music",
        "keywords": ("lyrics", "loi bai hat", "lời bài hát", "lyric video"),
        "aliases": (),
        "clip": ("song lyrics on screen", "lyric video text"),
    },
    {
        "slug": "kpop",
        "name": "K-Pop",
        "category": "kpop",
        "keywords": ("kpop", "k-pop", "bts", "blackpink", "twice", "straykids", "idol korea"),
        "aliases": (("nhac han", "vi"),),
        "clip": ("k-pop idol performance", "korean pop dance stage"),
    },
    {
        "slug": "vpop",
        "name": "V-Pop",
        "category": "vpop",
        "keywords": ("vpop", "v-pop", "nhạc việt", "nhac viet", "son tung", "hoang thuy linh"),
        "aliases": (),
        "clip": ("vietnamese pop music video", "v-pop singer"),
    },
    {
        "slug": "instruments",
        "name": "Instruments",
        "category": "instruments",
        "keywords": ("guitar", "piano", "violin", "drum", "ukulele", "saxophone", "nhạc cụ", "nhac cu"),
        "aliases": (("nh\u1ea1c c\u1ee5", "vi"),),
        "clip": ("person playing musical instrument", "guitar performance"),
    },
    {
        "slug": "karaoke",
        "name": "Karaoke",
        "category": "music",
        "keywords": ("karaoke", "hát karaoke", "hat karaoke"),
        "aliases": (),
        "clip": ("karaoke singing", "people singing karaoke"),
    },
    {
        "slug": "cover",
        "name": "Cover Song",
        "category": "music",
        "keywords": ("cover song", "covermusic", "hát cover", "hat cover"),
        "aliases": (),
        "clip": ("music cover performance", "singer covering a song"),
    },
    {
        "slug": "edm",
        "name": "EDM",
        "category": "music",
        "keywords": ("edm", "electronic dance", "techno", "house music", "dubstep"),
        "aliases": (),
        "clip": ("edm festival lights", "electronic dance music stage"),
    },
    {
        "slug": "rap",
        "name": "Rap",
        "category": "music",
        "keywords": ("rap", "hiphop", "hip-hop", "rapper", "freestyle rap"),
        "aliases": (),
        "clip": ("rapper performing", "hip hop music video"),
    },
    {
        "slug": "horror",
        "name": "Horror",
        "category": "horror",
        "keywords": ("horror", "ghost", "kinhdi", "kinh dị", "creepy", "ホラー", "truyenma", "truyện ma", "ma quái", "maquai", "true horror"),
        "aliases": (("kinhdi", "vi"), ("kinh d\u1ecb", "vi"), ("truy\u1ec7n ma", "vi"),),
        "clip": ("horror scene", "scary dark atmosphere", "creepy image"),
    },
    {
        "slug": "thriller",
        "name": "Thriller",
        "category": "thriller",
        "keywords": ("thriller", "giật gân", "giat gan", "suspense"),
        "aliases": (),
        "clip": ("thriller movie scene", "suspenseful dark scene"),
    },
    {
        "slug": "true_crime",
        "name": "True Crime",
        "category": "horror",
        "keywords": ("true crime", "truecrime", "an mang", "án mạng"),
        "aliases": (),
        "clip": ("true crime documentary style", "crime investigation footage"),
    },
    {
        "slug": "gaming",
        "name": "Gaming",
        "category": "gaming",
        "keywords": ("gaming", "gameplay", "gamer", "esports", "stream game"),
        "aliases": (("game", "en"),),
        "clip": ("video game gameplay", "gaming screen", "esports match"),
    },
    {
        "slug": "valorant",
        "name": "Valorant",
        "category": "gaming",
        "keywords": ("valorant", "valo"),
        "aliases": (),
        "clip": ("valorant gameplay", "valorant fps match"),
    },
    {
        "slug": "league_of_legends",
        "name": "League of Legends",
        "category": "gaming",
        "keywords": ("league of legends", "lienminh", "liên minh", "lol game"),
        "aliases": (("lienminh", "vi"),),
        "clip": ("league of legends gameplay", "moba match screen"),
    },
    {
        "slug": "minecraft",
        "name": "Minecraft",
        "category": "gaming",
        "keywords": ("minecraft", "mcpe", "mine craft"),
        "aliases": (),
        "clip": ("minecraft gameplay", "minecraft building"),
    },
    {
        "slug": "freefire",
        "name": "Free Fire",
        "category": "gaming",
        "keywords": ("freefire", "free fire", "ff max"),
        "aliases": (),
        "clip": ("free fire gameplay", "garena free fire"),
    },
    {
        "slug": "pubg",
        "name": "PUBG",
        "category": "gaming",
        "keywords": ("pubg", "battlegrounds", "bgmi"),
        "aliases": (),
        "clip": ("pubg gameplay", "battle royale shooting"),
    },
    {
        "slug": "genshin",
        "name": "Genshin Impact",
        "category": "gaming",
        "keywords": ("genshin", "genshin impact", "hoyoverse"),
        "aliases": (),
        "clip": ("genshin impact gameplay", "anime style open world game"),
    },
    {
        "slug": "roblox",
        "name": "Roblox",
        "category": "gaming",
        "keywords": ("roblox"),
        "aliases": (),
        "clip": ("roblox gameplay", "roblox avatar world"),
    },
    {
        "slug": "mobile_legends",
        "name": "Mobile Legends",
        "category": "gaming",
        "keywords": ("mobile legends", "mlbb", "lienquan", "liên quân"),
        "aliases": (("lienquan", "vi"),),
        "clip": ("mobile legends gameplay", "mlbb match"),
    },
    {
        "slug": "food",
        "name": "Food",
        "category": "food",
        "keywords": ("food", "amthuc", "ẩm thực", "an uong", "ăn uống", "đồ ăn", "do an", "cooking food"),
        "aliases": (("amthuc", "vi"), ("\u1ea9m th\u1ef1c", "vi"), ("\u0111\u1ed3 \u0103n", "vi"),),
        "clip": ("vietnamese food", "street food dish", "cooking food"),
    },
    {
        "slug": "mukbang",
        "name": "Mukbang",
        "category": "mukbang",
        "keywords": ("mukbang", "an mukbang", "ăn mukbang", "eatwithme"),
        "aliases": (),
        "clip": ("mukbang eating show", "person eating large meal"),
    },
    {
        "slug": "street_food",
        "name": "Street Food",
        "category": "streetfood",
        "keywords": ("street food", "streetfood", "an vat", "ăn vặt", "quan via he", "quán vỉa hè"),
        "aliases": (("\u0103n v\u1eb7t", "vi"),),
        "clip": ("vietnamese street food", "street vendor food"),
    },
    {
        "slug": "vietnamese_food",
        "name": "Vietnamese Food",
        "category": "food",
        "keywords": ("pho", "phở", "bun bo", "bún bò", "banh mi", "bánh mì", "com tam", "cơm tấm", "bun cha", "bún chả"),
        "aliases": (),
        "clip": ("vietnamese pho bowl", "banh mi sandwich"),
    },
    {
        "slug": "cooking",
        "name": "Cooking",
        "category": "food",
        "keywords": ("cooking", "nau an", "nấu ăn", "recipe", "cong thuc", "công thức"),
        "aliases": (("n\u1ea5u \u0103n", "vi"),),
        "clip": ("home cooking", "chef preparing food"),
    },
    {
        "slug": "dessert",
        "name": "Dessert",
        "category": "food",
        "keywords": ("dessert", "banh ngot", "bánh ngọt", "cake", "cookies", "che", "chè"),
        "aliases": (),
        "clip": ("dessert cake", "sweet dessert plating"),
    },
    {
        "slug": "coffee",
        "name": "Coffee",
        "category": "food",
        "keywords": ("coffee", "cafe", "cà phê", "ca phe", "espresso", "latte"),
        "aliases": (("c\u00e0 ph\u00ea", "vi"),),
        "clip": ("coffee cup", "cafe latte art"),
    },
    {
        "slug": "travel",
        "name": "Travel",
        "category": "travel",
        "keywords": ("travel", "dulich", "du lịch", "dalat", "đà lạt", "beach trip", "du lich"),
        "aliases": (("dulich", "vi"), ("du l\u1ecbch", "vi"),),
        "clip": ("travel scenery", "beach landscape", "city travel vlog"),
    },
    {
        "slug": "camping",
        "name": "Camping",
        "category": "camping",
        "keywords": ("camping", "cam trai", "cắm trại", "tent", "picnic"),
        "aliases": (("c\u1eafm tr\u1ea1i", "vi"),),
        "clip": ("camping tent outdoors", "campfire night"),
    },
    {
        "slug": "nature",
        "name": "Nature",
        "category": "nature",
        "keywords": ("nature", "thien nhien", "thiên nhiên", "forest", "waterfall", "doi nui"),
        "aliases": (("thi\u00ean nhi\u00ean", "vi"),),
        "clip": ("beautiful nature landscape", "forest waterfall"),
    },
    {
        "slug": "fishing",
        "name": "Fishing",
        "category": "fishing",
        "keywords": ("fishing", "cau ca", "câu cá", "angler"),
        "aliases": (("c\u00e2u c\u00e1", "vi"),),
        "clip": ("person fishing", "fishing by the lake"),
    },
    {
        "slug": "farming",
        "name": "Farming",
        "category": "farming",
        "keywords": ("farming", "nong nghiep", "nông nghiệp", "nong trai", "nông trại", "rua cay"),
        "aliases": (("n\u00f4ng nghi\u1ec7p", "vi"),),
        "clip": ("farming field", "farmer working crops"),
    },
    {
        "slug": "comedy",
        "name": "Comedy",
        "category": "comedy",
        "keywords": ("comedy", "funny", "haihuoc", "hài hước", "hài", "standup"),
        "aliases": (("h\u00e0i", "vi"), ("h\u00e0i h\u01b0\u1edbc", "vi"),),
        "clip": ("funny comedy sketch", "people laughing"),
    },
    {
        "slug": "meme",
        "name": "Meme",
        "category": "meme",
        "keywords": ("meme", "shitpost", "dank meme"),
        "aliases": (),
        "clip": ("internet meme image", "funny meme format"),
    },
    {
        "slug": "prank",
        "name": "Prank",
        "category": "prank",
        "keywords": ("prank", "tro dua", "trò đùa", "pranking"),
        "aliases": (),
        "clip": ("prank video", "people pranking"),
    },
    {
        "slug": "challenge",
        "name": "Challenge",
        "category": "challenge",
        "keywords": ("challenge", "thu thach", "thử thách", "trend challenge"),
        "aliases": (("th\u1eed th\u00e1ch", "vi"),),
        "clip": ("social media challenge", "people doing a challenge"),
    },
    {
        "slug": "reaction",
        "name": "Reaction",
        "category": "reaction",
        "keywords": ("reaction", "react", "phan ung", "phản ứng"),
        "aliases": (),
        "clip": ("reaction video face", "person reacting to video"),
    },
    {
        "slug": "viral",
        "name": "Viral",
        "category": "viral",
        "keywords": ("viral", "trending video", "clip hot"),
        "aliases": (),
        "clip": ("viral social media clip"),
    },
    {
        "slug": "education",
        "name": "Education",
        "category": "education",
        "keywords": ("education", "tutorial", "learning", "hoc", "học", "bai giang", "bài giảng"),
        "aliases": (("h\u1ecdc", "vi"),),
        "clip": ("classroom lecture", "educational tutorial screen"),
    },
    {
        "slug": "coding",
        "name": "Coding",
        "category": "technology",
        "keywords": ("coding", "laptrinh", "lập trình", "programmer", "docker", "postgresql", "python code", "javascript"),
        "aliases": (("laptrinh", "vi"), ("l\u1eadp tr\u00ecnh", "vi"), ("java", "en"),),
        "clip": ("programmer at computer", "code on screen"),
    },
    {
        "slug": "technology",
        "name": "Technology",
        "category": "technology",
        "keywords": ("technology", "tech", "cong nghe", "công nghệ", "gadget"),
        "aliases": (("c\u00f4ng ngh\u1ec7", "vi"),),
        "clip": ("tech gadgets", "modern technology devices"),
    },
    {
        "slug": "ai",
        "name": "Artificial Intelligence",
        "category": "technology",
        "keywords": ("artificial intelligence", "chatgpt", "machine learning", "ai tool", "openai"),
        "aliases": (("tri tue nhan tao", "vi"),),
        "clip": ("artificial intelligence concept", "ai robot interface"),
    },
    {
        "slug": "unboxing",
        "name": "Unboxing",
        "category": "unboxing",
        "keywords": ("unboxing", "mo hop", "mở hộp"),
        "aliases": (("m\u1edf h\u1ed9p", "vi"),),
        "clip": ("product unboxing", "opening a package"),
    },
    {
        "slug": "review",
        "name": "Review",
        "category": "review",
        "keywords": ("review", "danh gia", "đánh giá", "tren tay"),
        "aliases": (("\u0111\u00e1nh gi\u00e1", "vi"),),
        "clip": ("product review", "person reviewing gadget"),
    },
    {
        "slug": "beauty",
        "name": "Beauty",
        "category": "beauty",
        "keywords": ("beauty", "makeup", "skincare", "lam dep", "làm đẹp", "my pham", "mỹ phẩm"),
        "aliases": (("l\u00e0m \u0111\u1eb9p", "vi"),),
        "clip": ("beauty makeup tutorial", "skincare routine"),
    },
    {
        "slug": "makeup",
        "name": "Makeup",
        "category": "beauty",
        "keywords": ("makeup", "trang diem", "trang điểm", "eyeliner", "lipstick"),
        "aliases": (("trang \u0111i\u1ec3m", "vi"),),
        "clip": ("makeup application", "beauty makeup closeup"),
    },
    {
        "slug": "skincare",
        "name": "Skincare",
        "category": "beauty",
        "keywords": ("skincare", "cham soc da", "chăm sóc da", "serum", "moisturizer"),
        "aliases": (("ch\u0103m s\u00f3c da", "vi"),),
        "clip": ("skincare products", "facial skincare routine"),
    },
    {
        "slug": "fashion",
        "name": "Fashion",
        "category": "fashion",
        "keywords": ("fashion", "outfit", "ootd", "thoi trang", "thời trang", "style"),
        "aliases": (("th\u1eddi trang", "vi"),),
        "clip": ("fashion outfit", "street style clothing"),
    },
    {
        "slug": "fitness",
        "name": "Fitness",
        "category": "fitness",
        "keywords": ("fitness", "gym", "workout", "tap gym", "tập gym", "bodybuilding"),
        "aliases": (),
        "clip": ("gym workout", "person exercising fitness"),
    },
    {
        "slug": "yoga",
        "name": "Yoga",
        "category": "fitness",
        "keywords": ("yoga", "pilates", "stretching"),
        "aliases": (),
        "clip": ("yoga pose", "person doing yoga"),
    },
    {
        "slug": "sports",
        "name": "Sports",
        "category": "sports",
        "keywords": ("sports", "the thao", "thể thao", "athlete"),
        "aliases": (("th\u1ec3 thao", "vi"),),
        "clip": ("sports match", "athletes competing"),
    },
    {
        "slug": "football",
        "name": "Football",
        "category": "sports",
        "keywords": ("football", "soccer", "bongda", "bóng đá", "fifa"),
        "aliases": (("b\u00f3ng \u0111\u00e1", "vi"),),
        "clip": ("football soccer match", "soccer players"),
    },
    {
        "slug": "basketball",
        "name": "Basketball",
        "category": "sports",
        "keywords": ("basketball", "bong ro", "bóng rổ", "nba"),
        "aliases": (("b\u00f3ng r\u1ed5", "vi"),),
        "clip": ("basketball game", "dunk basketball"),
    },
    {
        "slug": "mma",
        "name": "MMA",
        "category": "sports",
        "keywords": ("mma", "ufc", "boxing", "kickboxing", "muay thai"),
        "aliases": (),
        "clip": ("mma fight", "boxing match"),
    },
    {
        "slug": "family",
        "name": "Family",
        "category": "family",
        "keywords": ("family", "gia dinh", "gia đình", "family life", "parenting"),
        "aliases": (("gia \u0111\u00ecnh", "vi"),),
        "clip": ("happy family together", "family home life"),
    },
    {
        "slug": "kids",
        "name": "Kids",
        "category": "kids",
        "keywords": ("kids", "tre em", "trẻ em", "baby", "em be", "em bé", "toddler"),
        "aliases": (("tr\u1ebb em", "vi"),),
        "clip": ("children playing", "cute baby"),
    },
    {
        "slug": "pets",
        "name": "Pets",
        "category": "pets",
        "keywords": ("pets", "thu cung", "thú cưng", "pet care"),
        "aliases": (("th\u00fa c\u01b0ng", "vi"),),
        "clip": ("cute pet animals", "pet care"),
    },
    {
        "slug": "cat",
        "name": "Cat",
        "category": "pets",
        "keywords": ("cat", "meo", "mèo", "kitten", "meow"),
        "aliases": (("m\u00e8o", "vi"),),
        "clip": ("a photo of a cat", "cute cat"),
    },
    {
        "slug": "dog",
        "name": "Dog",
        "category": "pets",
        "keywords": ("dog", "cho", "chó", "puppy", "corgi"),
        "aliases": (("ch\u00f3", "vi"),),
        "clip": ("a photo of a dog", "cute dog"),
    },
    {
        "slug": "night",
        "name": "Night",
        "category": "lifestyle",
        "keywords": ("night", "dem khuya", "đêm khuya", "midnight", "city night"),
        "aliases": (("\u0111\u00eam", "vi"),),
        "clip": ("night city lights", "dark night scene"),
    },
    {
        "slug": "sad",
        "name": "Sad",
        "category": "lifestyle",
        "keywords": ("sad", "buon", "buồn", "melancholy", "tam trạng buồn"),
        "aliases": (("bu\u1ed3n", "vi"),),
        "clip": ("sad emotional scene", "melancholy mood"),
    },
    {
        "slug": "city",
        "name": "City",
        "category": "travel",
        "keywords": ("city", "thanh pho", "thành phố", "saigon", "hanoi", "hà nội", "urban"),
        "aliases": (("th\u00e0nh ph\u1ed1", "vi"),),
        "clip": ("city skyline", "urban street"),
    },
    {
        "slug": "rain",
        "name": "Rain",
        "category": "nature",
        "keywords": ("rain", "mua", "mưa", "rainy", "mưa rơi"),
        "aliases": (("m\u01b0a", "vi"),),
        "clip": ("rainy weather", "rain on window"),
    },
    {
        "slug": "girl",
        "name": "Girl",
        "category": "lifestyle",
        "keywords": ("girl", "con gai", "cô gái", "women portrait"),
        "aliases": (("c\u00f4 g\u00e1i", "vi"),),
        "clip": ("young woman portrait", "girl selfie"),
    },
    {
        "slug": "boy",
        "name": "Boy",
        "category": "lifestyle",
        "keywords": ("boy", "con trai", "chàng trai", "men portrait"),
        "aliases": (("ch\u00e0ng trai", "vi"),),
        "clip": ("young man portrait", "boy selfie"),
    },
    {
        "slug": "movies",
        "name": "Movies",
        "category": "movies",
        "keywords": ("movie", "movies", "phim", "cinema", "film review"),
        "aliases": (("phim", "vi"),),
        "clip": ("movie cinema scene", "film still"),
    },
    {
        "slug": "documentary",
        "name": "Documentary",
        "category": "documentary",
        "keywords": ("documentary", "phim tai lieu", "phim tài liệu"),
        "aliases": (),
        "clip": ("documentary footage", "documentary interview"),
    },
    {
        "slug": "action",
        "name": "Action",
        "category": "action",
        "keywords": ("action movie", "hanh dong", "hành động", "action scene"),
        "aliases": (("h\u00e0nh \u0111\u1ed9ng", "vi"),),
        "clip": ("action movie fight", "explosive action scene"),
    },
    {
        "slug": "romance",
        "name": "Romance",
        "category": "romance",
        "keywords": ("romance", "tinh cam", "tình cảm", "love story", "ngon tinh"),
        "aliases": (("t\u00ecnh c\u1ea3m", "vi"),),
        "clip": ("romantic couple", "romance movie scene"),
    },
    {
        "slug": "scifi",
        "name": "Sci-Fi",
        "category": "scifi",
        "keywords": ("scifi", "sci-fi", "khoa hoc vien tuong", "science fiction"),
        "aliases": (),
        "clip": ("science fiction scene", "futuristic sci-fi"),
    },
    {
        "slug": "magic",
        "name": "Magic",
        "category": "magic",
        "keywords": ("magic", "ao thuat", "ảo thuật", "magician", "card trick"),
        "aliases": (("\u1ea3o thu\u1eadt", "vi"),),
        "clip": ("magician performing trick", "stage magic"),
    },
    {
        "slug": "dance",
        "name": "Dance",
        "category": "dance",
        "keywords": ("dance", "nhay", "nhảy", "choreography", "dance cover", "kpop dance"),
        "aliases": (("nh\u1ea3y", "vi"),),
        "clip": ("people dancing", "dance choreography"),
    },
    {
        "slug": "art",
        "name": "Art",
        "category": "art",
        "keywords": ("art", "drawing", "painting", "sketch", "ve tranh", "vẽ tranh"),
        "aliases": (("v\u1ebd", "vi"),),
        "clip": ("artist drawing", "painting artwork"),
    },
    {
        "slug": "photography",
        "name": "Photography",
        "category": "photography",
        "keywords": ("photography", "nhiep anh", "nhiếp ảnh", "photographer", "camera gear"),
        "aliases": (("nhi\u1ebfp \u1ea3nh", "vi"),),
        "clip": ("photographer with camera", "photography session"),
    },
    {
        "slug": "diy",
        "name": "DIY",
        "category": "diy",
        "keywords": ("diy", "handmade", "do it yourself", "thu cong", "thủ công"),
        "aliases": (),
        "clip": ("diy craft project", "handmade crafting"),
    },
    {
        "slug": "asmr",
        "name": "ASMR",
        "category": "asmr",
        "keywords": ("asmr", "tingles", "whisper asmr"),
        "aliases": (),
        "clip": ("asmr microphone closeup", "asmr whispering"),
    },
    {
        "slug": "lifestyle",
        "name": "Lifestyle",
        "category": "lifestyle",
        "keywords": ("lifestyle", "daily vlog", "cuoc song", "cuộc sống", "day in my life"),
        "aliases": (),
        "clip": ("daily lifestyle vlog", "everyday life scenes"),
    },
    {
        "slug": "motivation",
        "name": "Motivation",
        "category": "motivation",
        "keywords": ("motivation", "motivational", "dong luc", "động lực", "inspiration"),
        "aliases": (("\u0111\u1ed9ng l\u1ef1c", "vi"),),
        "clip": ("motivational speech", "inspirational success"),
    },
    {
        "slug": "career",
        "name": "Career",
        "category": "career",
        "keywords": ("career", "su nghiep", "sự nghiệp", "job tips", "interview tips"),
        "aliases": (("s\u1ef1 nghi\u1ec7p", "vi"),),
        "clip": ("office career work", "professional workplace"),
    },
    {
        "slug": "finance",
        "name": "Finance",
        "category": "finance",
        "keywords": ("finance", "investment", "chung khoan", "chứng khoán", "tai chinh", "tài chính", "money tips"),
        "aliases": (("t\u00e0i ch\u00ednh", "vi"),),
        "clip": ("finance charts", "money investment"),
    },
    {
        "slug": "crypto",
        "name": "Crypto",
        "category": "finance",
        "keywords": ("crypto", "bitcoin", "ethereum", "nft", "blockchain"),
        "aliases": (),
        "clip": ("cryptocurrency charts", "bitcoin trading"),
    },
    {
        "slug": "realestate",
        "name": "Real Estate",
        "category": "realestate",
        "keywords": ("realestate", "real estate", "bat dong san", "bất động sản", "can ho", "căn hộ"),
        "aliases": (("b\u1ea5t \u0111\u1ed9ng s\u1ea3n", "vi"),),
        "clip": ("real estate apartment", "house property tour"),
    },
    {
        "slug": "health",
        "name": "Health",
        "category": "health",
        "keywords": ("health", "suc khoe", "sức khỏe", "healthy living", "wellness"),
        "aliases": (("s\u1ee9c kh\u1ecfe", "vi"),),
        "clip": ("healthy lifestyle", "medical wellness"),
    },
    {
        "slug": "nutrition",
        "name": "Nutrition",
        "category": "health",
        "keywords": ("nutrition", "dinh duong", "dinh dưỡng", "diet", "calorie"),
        "aliases": (("dinh d\u01b0\u1ee1ng", "vi"),),
        "clip": ("healthy nutrition meal", "balanced diet food"),
    },
    {
        "slug": "relationships",
        "name": "Relationships",
        "category": "relationships",
        "keywords": ("relationships", "dating tips", "tinh yeu", "tình yêu", "relationship advice"),
        "aliases": (),
        "clip": ("couple relationship", "dating couple"),
    },
    {
        "slug": "wedding",
        "name": "Wedding",
        "category": "wedding",
        "keywords": ("wedding", "dam cuoi", "đám cưới", "bride", "groom", "vu quy"),
        "aliases": (("\u0111\u00e1m c\u01b0\u1edbi", "vi"),),
        "clip": ("wedding ceremony", "bride and groom"),
    },
    {
        "slug": "spirituality",
        "name": "Spirituality",
        "category": "spirituality",
        "keywords": ("spirituality", "meditation", "mindfulness", "spiritual", "thien"),
        "aliases": (),
        "clip": ("meditation spirituality", "peaceful mindfulness"),
    },
    {
        "slug": "podcast",
        "name": "Podcast",
        "category": "podcast",
        "keywords": ("podcast", "talkshow", "audio talk"),
        "aliases": (),
        "clip": ("podcast microphone", "people recording podcast"),
    },
    {
        "slug": "books",
        "name": "Books",
        "category": "books",
        "keywords": ("books", "reading", "sach", "sách", "booktok", "book review"),
        "aliases": (("s\u00e1ch", "vi"),),
        "clip": ("person reading book", "stack of books"),
    },
    {
        "slug": "science",
        "name": "Science",
        "category": "science",
        "keywords": ("science", "khoa hoc", "khoa học", "physics", "chemistry", "biology"),
        "aliases": (("khoa h\u1ecdc", "vi"),),
        "clip": ("science laboratory", "scientific experiment"),
    },
    {
        "slug": "history",
        "name": "History",
        "category": "history",
        "keywords": ("history", "lich su", "lịch sử", "historical"),
        "aliases": (("l\u1ecbch s\u1eed", "vi"),),
        "clip": ("historical documentary", "history museum"),
    },
    {
        "slug": "language",
        "name": "Language Learning",
        "category": "language",
        "keywords": ("language learning", "english learning", "ngoai ngu", "ngoại ngữ", "ielts", "toeic"),
        "aliases": (("ngo\u1ea1i ng\u1eef", "vi"),),
        "clip": ("language learning classroom", "english study"),
    },
    {
        "slug": "news",
        "name": "News",
        "category": "news",
        "keywords": ("news", "breaking news", "tin tuc", "tin tức", "thoi su", "thời sự"),
        "aliases": (("tin t\u1ee9c", "vi"),),
        "clip": ("news broadcast", "news reporter"),
    },
    {
        "slug": "automotive",
        "name": "Automotive",
        "category": "automotive",
        "keywords": ("automotive", "car review", "xe hơi", "xe hoi", "supercar"),
        "aliases": (),
        "clip": ("car automotive", "vehicle on road"),
    },
    {
        "slug": "motorcycle",
        "name": "Motorcycle",
        "category": "automotive",
        "keywords": ("motorcycle", "xe may", "xe máy", "motorbike", "motor"),
        "aliases": (("xe m\u00e1y", "vi"),),
        "clip": ("motorcycle on street", "motorbike rider"),
    },
    {
        "slug": "electric_vehicle",
        "name": "Electric Vehicle",
        "category": "automotive",
        "keywords": ("electric vehicle", "ev car", "tesla", "vinfast", "xe điện", "xe dien"),
        "aliases": (),
        "clip": ("electric car", "ev charging station"),
    },
    {
        "slug": "aesthetic",
        "name": "Aesthetic",
        "category": "lifestyle",
        "keywords": ("aesthetic", "aesthetics", "soft girl", "dark academia"),
        "aliases": (),
        "clip": ("aesthetic photography", "aesthetic room decor"),
    },
    {
        "slug": "vlog",
        "name": "Vlog",
        "category": "lifestyle",
        "keywords": ("vlog", "daily vlog", "grwm", "get ready with me"),
        "aliases": (),
        "clip": ("personal vlog", "vlogger talking to camera"),
    },
    {
        "slug": "grwm",
        "name": "GRWM",
        "category": "beauty",
        "keywords": ("grwm", "get ready with me", "ready with me"),
        "aliases": (),
        "clip": ("get ready with me makeup", "morning grwm routine"),
    },
    {
        "slug": "haul",
        "name": "Haul",
        "category": "fashion",
        "keywords": ("haul", "shopping haul", "shein haul", "order haul"),
        "aliases": (),
        "clip": ("shopping haul clothes", "package haul"),
    },
    {
        "slug": "storytime",
        "name": "Storytime",
        "category": "comedy",
        "keywords": ("storytime", "story time", "kể chuyện", "ke chuyen"),
        "aliases": (),
        "clip": ("person telling story to camera"),
    },
    {
        "slug": "pov",
        "name": "POV",
        "category": "viral",
        "keywords": ("pov", "point of view", "pov video"),
        "aliases": (),
        "clip": ("pov first person video"),
    },
    {
        "slug": "satisfying",
        "name": "Satisfying",
        "category": "asmr",
        "keywords": ("satisfying", "oddly satisfying", "slime"),
        "aliases": (),
        "clip": ("oddly satisfying video", "satisfying slime"),
    },
    {
        "slug": "lifehacks",
        "name": "Life Hacks",
        "category": "diy",
        "keywords": ("lifehack", "life hacks", "meo hay", "mẹo hay", "tips and tricks"),
        "aliases": (("m\u1eb9o hay", "vi"),),
        "clip": ("life hack tip", "useful lifehack demo"),
    },
    {
        "slug": "cleaning",
        "name": "Cleaning",
        "category": "lifestyle",
        "keywords": ("cleaning", "don dep", "dọn dẹp", "clean with me"),
        "aliases": (("d\u1ecdn d\u1eb9p", "vi"),),
        "clip": ("home cleaning", "cleaning room"),
    },
    {
        "slug": "interior",
        "name": "Interior Design",
        "category": "lifestyle",
        "keywords": ("interior design", "home decor", "decor phong", "nội thất", "noi that"),
        "aliases": (),
        "clip": ("interior design room", "home decoration"),
    },
    {
        "slug": "garden",
        "name": "Garden",
        "category": "nature",
        "keywords": ("garden", "gardening", "trong cay", "trồng cây", "cay canh", "cây cảnh"),
        "aliases": (("tr\u1ed3ng c\u00e2y", "vi"),),
        "clip": ("garden plants", "home gardening"),
    },
    {
        "slug": "beach",
        "name": "Beach",
        "category": "travel",
        "keywords": ("beach", "bien", "biển", "seaside", "ocean"),
        "aliases": (("bi\u1ec3n", "vi"),),
        "clip": ("beach ocean waves", "seaside vacation"),
    },
    {
        "slug": "mountain",
        "name": "Mountain",
        "category": "travel",
        "keywords": ("mountain", "nui", "núi", "trekking", "hiking"),
        "aliases": (("n\u00fai", "vi"),),
        "clip": ("mountain hiking", "mountain landscape"),
    },
    {
        "slug": "foodtour",
        "name": "Food Tour",
        "category": "food",
        "keywords": ("food tour", "foodtour", "an khap", "ăn khắp", "checkin quan"),
        "aliases": (),
        "clip": ("food tour street", "restaurant hopping"),
    },
    {
        "slug": "bakery",
        "name": "Bakery",
        "category": "food",
        "keywords": ("bakery", "tiem banh", "tiệm bánh", "bread", "banh mi ngot"),
        "aliases": (),
        "clip": ("bakery bread", "pastry bakery"),
    },
    {
        "slug": "seafood",
        "name": "Seafood",
        "category": "food",
        "keywords": ("seafood", "hai san", "hải sản", "sushi", "sashimi"),
        "aliases": (("h\u1ea3i s\u1ea3n", "vi"),),
        "clip": ("seafood platter", "sushi seafood"),
    },
    {
        "slug": "bbq",
        "name": "BBQ",
        "category": "food",
        "keywords": ("bbq", "barbecue", "nuong", "nướng", "grill"),
        "aliases": (("n\u01b0\u1edbng", "vi"),),
        "clip": ("barbecue grill", "bbq meat"),
    },
    {
        "slug": "hotpot",
        "name": "Hotpot",
        "category": "food",
        "keywords": ("hotpot", "lau", "lẩu", "shabu"),
        "aliases": (("l\u1ea9u", "vi"),),
        "clip": ("hotpot boiling", "asian hotpot"),
    },
    {
        "slug": "drinks",
        "name": "Drinks",
        "category": "food",
        "keywords": ("drinks", "cocktail", "mocktail", "tra sua", "trà sữa", "bubble tea"),
        "aliases": (("tr\u00e0 s\u1eefa", "vi"),),
        "clip": ("colorful drinks", "bubble tea cup"),
    },
    {
        "slug": "wine",
        "name": "Wine",
        "category": "food",
        "keywords": ("wine", "ruou vang", "rượu vang", "wine tasting"),
        "aliases": (),
        "clip": ("wine glass tasting", "wine bottle"),
    },
    {
        "slug": "smartphone",
        "name": "Smartphone",
        "category": "technology",
        "keywords": ("smartphone", "iphone", "android phone", "dien thoai", "điện thoại"),
        "aliases": (("\u0111i\u1ec7n tho\u1ea1i", "vi"),),
        "clip": ("smartphone closeup", "mobile phone review"),
    },
    {
        "slug": "laptop",
        "name": "Laptop",
        "category": "technology",
        "keywords": ("laptop", "macbook", "notebook pc"),
        "aliases": (),
        "clip": ("laptop computer", "working on laptop"),
    },
    {
        "slug": "pc_build",
        "name": "PC Build",
        "category": "technology",
        "keywords": ("pc build", "custom pc", "rgb pc", "gaming pc"),
        "aliases": (),
        "clip": ("custom pc build", "rgb gaming computer"),
    },
    {
        "slug": "software",
        "name": "Software",
        "category": "technology",
        "keywords": ("software", "app review", "saas", "phan mem", "phần mềm"),
        "aliases": (),
        "clip": ("software interface", "app on screen"),
    },
    {
        "slug": "cybersecurity",
        "name": "Cybersecurity",
        "category": "technology",
        "keywords": ("cybersecurity", "hacking ethical", "infosec", "bao mat", "bảo mật"),
        "aliases": (),
        "clip": ("cybersecurity concept", "digital security"),
    },
    {
        "slug": "fortnite",
        "name": "Fortnite",
        "category": "gaming",
        "keywords": ("fortnite"),
        "aliases": (),
        "clip": ("fortnite gameplay"),
    },
    {
        "slug": "gta",
        "name": "GTA",
        "category": "gaming",
        "keywords": ("gta", "gta5", "gta v", "gta online"),
        "aliases": (),
        "clip": ("gta gameplay", "gta5 city"),
    },
    {
        "slug": "fps",
        "name": "FPS Games",
        "category": "gaming",
        "keywords": ("fps game", "first person shooter", "cs2", "counter strike", "call of duty"),
        "aliases": (),
        "clip": ("fps shooter gameplay"),
    },
    {
        "slug": "moba",
        "name": "MOBA",
        "category": "gaming",
        "keywords": ("moba", "dota", "arena of valor"),
        "aliases": (),
        "clip": ("moba game match"),
    },
    {
        "slug": "indie_game",
        "name": "Indie Game",
        "category": "gaming",
        "keywords": ("indie game", "indiegame"),
        "aliases": (),
        "clip": ("indie game footage"),
    },
    {
        "slug": "speedrun",
        "name": "Speedrun",
        "category": "gaming",
        "keywords": ("speedrun", "world record run"),
        "aliases": (),
        "clip": ("game speedrun timer"),
    },
    {
        "slug": "streamer",
        "name": "Streamer",
        "category": "gaming",
        "keywords": ("streamer", "twitch", "live stream", "streaming setup"),
        "aliases": (),
        "clip": ("streamer setup", "live streaming desk"),
    },
    {
        "slug": "rock",
        "name": "Rock",
        "category": "music",
        "keywords": ("rock music", "rock band", "metal music", "punk rock"),
        "aliases": (),
        "clip": ("rock band concert", "electric guitar rock"),
    },
    {
        "slug": "jazz",
        "name": "Jazz",
        "category": "music",
        "keywords": ("jazz", "jazz music", "saxophone jazz"),
        "aliases": (),
        "clip": ("jazz performance", "jazz club music"),
    },
    {
        "slug": "classical",
        "name": "Classical",
        "category": "music",
        "keywords": ("classical music", "orchestra", "symphony", "nhac giao huong"),
        "aliases": (),
        "clip": ("classical orchestra", "piano classical"),
    },
    {
        "slug": "ballad",
        "name": "Ballad",
        "category": "music",
        "keywords": ("ballad", "nhạc ballad", "love ballad"),
        "aliases": (),
        "clip": ("emotional ballad performance"),
    },
    {
        "slug": "remix",
        "name": "Remix",
        "category": "music",
        "keywords": ("remix", "mashup", "dj remix"),
        "aliases": (),
        "clip": ("dj remix booth", "music remix"),
    },
    {
        "slug": "ost",
        "name": "OST",
        "category": "music",
        "keywords": ("ost", "soundtrack", "nhạc phim", "nhac phim"),
        "aliases": (("nh\u1ea1c phim", "vi"),),
        "clip": ("movie soundtrack", "film ost"),
    },
    {
        "slug": "dance_challenge",
        "name": "Dance Challenge",
        "category": "dance",
        "keywords": ("dance challenge", "viral dance", "trend dance"),
        "aliases": (),
        "clip": ("viral dance challenge"),
    },
    {
        "slug": "ballet",
        "name": "Ballet",
        "category": "dance",
        "keywords": ("ballet", "balle"),
        "aliases": (),
        "clip": ("ballet dancer", "ballet performance"),
    },
    {
        "slug": "vietnam",
        "name": "Vietnam",
        "category": "travel",
        "keywords": ("vietnam", "viet nam", "việt nam", "vietnamese"),
        "aliases": (("vi\u1ec7t nam", "vi"),),
        "clip": ("vietnam travel", "vietnamese culture"),
    },
    {
        "slug": "hanoi",
        "name": "Hanoi",
        "category": "travel",
        "keywords": ("hanoi", "ha noi", "hà nội", "hoan kiem"),
        "aliases": (("h\u00e0 n\u1ed9i", "vi"),),
        "clip": ("hanoi old quarter", "hanoi street"),
    },
    {
        "slug": "saigon",
        "name": "Saigon",
        "category": "travel",
        "keywords": ("saigon", "ho chi minh", "sài gòn", "sai gon", "hcm city"),
        "aliases": (("s\u00e0i g\u00f2n", "vi"),),
        "clip": ("saigon city nights", "ho chi minh city"),
    },
    {
        "slug": "danang",
        "name": "Da Nang",
        "category": "travel",
        "keywords": ("danang", "da nang", "đà nẵng", "cau rong"),
        "aliases": (("\u0111\u00e0 n\u1eb5ng", "vi"),),
        "clip": ("da nang beach city"),
    },
    {
        "slug": "dalat",
        "name": "Da Lat",
        "category": "travel",
        "keywords": ("dalat", "da lat", "đà lạt", "da lat trip"),
        "aliases": (("\u0111\u00e0 l\u1ea1t", "vi"),),
        "clip": ("da lat pine hills", "da lat travel"),
    },
    {
        "slug": "phuquoc",
        "name": "Phu Quoc",
        "category": "travel",
        "keywords": ("phu quoc", "phú quốc", "dao phu quoc"),
        "aliases": (("ph\u00fa qu\u1ed1c", "vi"),),
        "clip": ("phu quoc island beach"),
    },
    {
        "slug": "halong",
        "name": "Ha Long",
        "category": "travel",
        "keywords": ("ha long", "halong", "hạ long", "vinh ha long"),
        "aliases": (("h\u1ea1 long", "vi"),),
        "clip": ("ha long bay boats"),
    },
    {
        "slug": "tet",
        "name": "Tet Holiday",
        "category": "lifestyle",
        "keywords": ("tet", "tết", "tet nguyen dan", "lunar new year vietnam"),
        "aliases": (("t\u1ebft", "vi"),),
        "clip": ("vietnamese tet celebration", "tet holiday family"),
    },
    {
        "slug": "mid_autumn",
        "name": "Mid-Autumn",
        "category": "lifestyle",
        "keywords": ("mid autumn", "tet trung thu", "tết trung thu", "mooncake"),
        "aliases": (("trung thu", "vi"),),
        "clip": ("mid autumn festival lanterns"),
    },
    {
        "slug": "bird",
        "name": "Bird",
        "category": "pets",
        "keywords": ("bird", "chim", "parrot", "sparrow"),
        "aliases": (),
        "clip": ("bird perched", "cute bird"),
    },
    {
        "slug": "fish",
        "name": "Fish",
        "category": "pets",
        "keywords": ("aquarium", "ca canh", "cá cảnh", "fish tank"),
        "aliases": (("c\u00e1 c\u1ea3nh", "vi"),),
        "clip": ("aquarium fish", "colorful fish"),
    },
    {
        "slug": "rabbit",
        "name": "Rabbit",
        "category": "pets",
        "keywords": ("rabbit", "bunny", "tho", "thỏ"),
        "aliases": (("th\u1ecf", "vi"),),
        "clip": ("cute rabbit", "bunny pet"),
    },
    {
        "slug": "hamster",
        "name": "Hamster",
        "category": "pets",
        "keywords": ("hamster"),
        "aliases": (),
        "clip": ("cute hamster"),
    },
    {
        "slug": "sunset",
        "name": "Sunset",
        "category": "nature",
        "keywords": ("sunset", "hoang hon", "hoàng hôn", "sunrise", "binh minh", "bình minh"),
        "aliases": (("ho\u00e0ng h\u00f4n", "vi"),),
        "clip": ("beautiful sunset sky", "golden hour sunset"),
    },
    {
        "slug": "flowers",
        "name": "Flowers",
        "category": "nature",
        "keywords": ("flowers", "hoa", "bouquet", "hoa dep"),
        "aliases": (),
        "clip": ("beautiful flowers", "flower garden"),
    },
    {
        "slug": "snow",
        "name": "Snow",
        "category": "nature",
        "keywords": ("snow", "tuyet", "tuyết", "snowfall"),
        "aliases": (("tuy\u1ebft", "vi"),),
        "clip": ("snowy landscape", "falling snow"),
    },
    {
        "slug": "study_with_me",
        "name": "Study With Me",
        "category": "education",
        "keywords": ("study with me", "studywithme", "pomodoro study"),
        "aliases": (),
        "clip": ("study with me desk", "student studying"),
    },
    {
        "slug": "exam",
        "name": "Exam",
        "category": "education",
        "keywords": ("exam", "thi cu", "kỳ thi", "ky thi", "on thi", "ôn thi"),
        "aliases": (("\u00f4n thi", "vi"),),
        "clip": ("students taking exam", "exam preparation"),
    },
    {
        "slug": "math",
        "name": "Math",
        "category": "education",
        "keywords": ("math", "toan", "toán", "algebra", "geometry"),
        "aliases": (("to\u00e1n", "vi"),),
        "clip": ("math equations on board"),
    },
    {
        "slug": "english",
        "name": "English",
        "category": "language",
        "keywords": ("learn english", "english tips", "tieng anh", "tiếng anh"),
        "aliases": (("ti\u1ebfng anh", "vi"),),
        "clip": ("english learning", "english vocabulary"),
    },
    {
        "slug": "japanese",
        "name": "Japanese",
        "category": "language",
        "keywords": ("learn japanese", "tieng nhat", "tiếng nhật", "nihongo", "jlpt"),
        "aliases": (("ti\u1ebfng nh\u1eadt", "vi"),),
        "clip": ("japanese language study"),
    },
    {
        "slug": "korean",
        "name": "Korean",
        "category": "language",
        "keywords": ("learn korean", "tieng han", "tiếng hàn", "hangul"),
        "aliases": (("ti\u1ebfng h\u00e0n", "vi"),),
        "clip": ("korean language study"),
    },
    {
        "slug": "university",
        "name": "University",
        "category": "education",
        "keywords": ("university", "campus", "dai hoc", "đại học", "sinh vien", "sinh viên"),
        "aliases": (("\u0111\u1ea1i h\u1ecdc", "vi"),),
        "clip": ("university campus", "college students"),
    },
    {
        "slug": "remote_work",
        "name": "Remote Work",
        "category": "career",
        "keywords": ("remote work", "work from home", "wfh", "digital nomad"),
        "aliases": (),
        "clip": ("remote work laptop", "work from home desk"),
    },
    {
        "slug": "side_hustle",
        "name": "Side Hustle",
        "category": "career",
        "keywords": ("side hustle", "kiem tien online", "kiếm tiền online", "passive income"),
        "aliases": (("ki\u1ebfm ti\u1ec1n", "vi"),),
        "clip": ("side hustle entrepreneurship"),
    },
    {
        "slug": "running",
        "name": "Running",
        "category": "sports",
        "keywords": ("running", "chay bo", "chạy bộ", "marathon", "jogging"),
        "aliases": (("ch\u1ea1y b\u1ed9", "vi"),),
        "clip": ("person running outdoors"),
    },
    {
        "slug": "cycling",
        "name": "Cycling",
        "category": "sports",
        "keywords": ("cycling", "dap xe", "đạp xe", "bike ride"),
        "aliases": (("\u0111\u1ea1p xe", "vi"),),
        "clip": ("person cycling", "road bike"),
    },
    {
        "slug": "swimming",
        "name": "Swimming",
        "category": "sports",
        "keywords": ("swimming", "boi loi", "bơi lội", "pool swim"),
        "aliases": (("b\u01a1i", "vi"),),
        "clip": ("person swimming pool"),
    },
    {
        "slug": "badminton",
        "name": "Badminton",
        "category": "sports",
        "keywords": ("badminton", "cau long", "cầu lông"),
        "aliases": (("c\u1ea7u l\u00f4ng", "vi"),),
        "clip": ("badminton match"),
    },
    {
        "slug": "volleyball",
        "name": "Volleyball",
        "category": "sports",
        "keywords": ("volleyball", "bong chuyen", "bóng chuyền"),
        "aliases": (("b\u00f3ng chuy\u1ec1n", "vi"),),
        "clip": ("volleyball game"),
    },
    {
        "slug": "esports_tournament",
        "name": "Esports Tournament",
        "category": "gaming",
        "keywords": ("esports tournament", "giai dau game", "giải đấu game"),
        "aliases": (),
        "clip": ("esports arena tournament"),
    },
    {
        "slug": "happy",
        "name": "Happy",
        "category": "lifestyle",
        "keywords": ("happy", "vui ve", "vui vẻ", "joyful", "smile"),
        "aliases": (("vui v\u1ebb", "vi"),),
        "clip": ("happy smiling people"),
    },
    {
        "slug": "relax",
        "name": "Relax",
        "category": "lifestyle",
        "keywords": ("relax", "thu gian", "thư giãn", "calm", "peaceful"),
        "aliases": (("th\u01b0 gi\u00e3n", "vi"),),
        "clip": ("relaxing calm scene"),
    },
    {
        "slug": "motovlog",
        "name": "Motovlog",
        "category": "automotive",
        "keywords": ("motovlog", "moto vlog", "ride vlog"),
        "aliases": (),
        "clip": ("motorcycle vlog riding"),
    },
    {
        "slug": "car_vlog",
        "name": "Car Vlog",
        "category": "automotive",
        "keywords": ("car vlog", "dashboard cam", "drive with me"),
        "aliases": (),
        "clip": ("car driving vlog"),
    },
    {
        "slug": "transformation",
        "name": "Transformation",
        "category": "fitness",
        "keywords": ("transformation", "before after", "glow up", "weight loss journey"),
        "aliases": (),
        "clip": ("fitness transformation before after"),
    },
    {
        "slug": "outfit_ideas",
        "name": "Outfit Ideas",
        "category": "fashion",
        "keywords": ("outfit ideas", "what i wore", "style tips"),
        "aliases": (),
        "clip": ("fashion outfit ideas"),
    },
    {
        "slug": "streetwear",
        "name": "Streetwear",
        "category": "fashion",
        "keywords": ("streetwear", "sneakers", "sneakerhead"),
        "aliases": (),
        "clip": ("streetwear fashion sneakers"),
    },
    {
        "slug": "luxury",
        "name": "Luxury",
        "category": "fashion",
        "keywords": ("luxury", "high fashion", "designer brand"),
        "aliases": (),
        "clip": ("luxury fashion brand"),
    },
    {
        "slug": "minimalism",
        "name": "Minimalism",
        "category": "lifestyle",
        "keywords": ("minimalism", "minimalist", "declutter"),
        "aliases": (),
        "clip": ("minimalist lifestyle room"),
    },
    {
        "slug": "horror_game",
        "name": "Horror Game",
        "category": "gaming",
        "keywords": ("horror game", "scary game", "resident evil", "outlast"),
        "aliases": (),
        "clip": ("horror video game", "scary game gameplay"),
    },
    {
        "slug": "gacha",
        "name": "Gacha",
        "category": "gaming",
        "keywords": ("gacha", "wish genshin", "pull banner"),
        "aliases": (),
        "clip": ("gacha game pull animation"),
    },
    {
        "slug": "anime_edit",
        "name": "Anime Edit",
        "category": "anime",
        "keywords": ("anime edit", "amv", "anime amv", "anime clip"),
        "aliases": (),
        "clip": ("anime edit video", "anime amv"),
    },
    {
        "slug": "manga_review",
        "name": "Manga Review",
        "category": "anime",
        "keywords": ("manga review", "spoiler manga"),
        "aliases": (),
        "clip": ("manga pages review"),
    },
    {
        "slug": "kdrama",
        "name": "K-Drama",
        "category": "movies",
        "keywords": ("kdrama", "k-drama", "korean drama", "phim han"),
        "aliases": (),
        "clip": ("korean drama scene"),
    },
    {
        "slug": "cdrama",
        "name": "C-Drama",
        "category": "movies",
        "keywords": ("cdrama", "c-drama", "chinese drama", "phim trung"),
        "aliases": (),
        "clip": ("chinese drama scene"),
    },
    {
        "slug": "tvshow",
        "name": "TV Show",
        "category": "movies",
        "keywords": ("tv show", "series", "season finale", "binge watch"),
        "aliases": (),
        "clip": ("tv series scene"),
    },
    {
        "slug": "stand_up",
        "name": "Stand-up",
        "category": "comedy",
        "keywords": ("standup comedy", "stand-up", "comedy club"),
        "aliases": (),
        "clip": ("standup comedian on stage"),
    },
    {
        "slug": "sketch",
        "name": "Sketch Comedy",
        "category": "comedy",
        "keywords": ("sketch comedy", "hài sketch", "comedy sketch"),
        "aliases": (),
        "clip": ("comedy sketch performance"),
    },
    {
        "slug": "dub",
        "name": "Dub / Voiceover",
        "category": "comedy",
        "keywords": ("dubbing", "voiceover", "long tieng", "lồng tiếng"),
        "aliases": (("l\u1ed3ng ti\u1ebfng", "vi"),),
        "clip": ("voiceover dubbing"),
    },
    {
        "slug": "animation",
        "name": "Animation",
        "category": "art",
        "keywords": ("animation", "2d animation", "3d animation", "hoat hinh", "hoạt hình"),
        "aliases": (("ho\u1ea1t h\u00ecnh", "vi"),),
        "clip": ("animated cartoon", "3d animation"),
    },
    {
        "slug": "digital_art",
        "name": "Digital Art",
        "category": "art",
        "keywords": ("digital art", "procreate", "illustration", "drawing process"),
        "aliases": (),
        "clip": ("digital art illustration"),
    },
    {
        "slug": "calligraphy",
        "name": "Calligraphy",
        "category": "art",
        "keywords": ("calligraphy", "thu phap", "thư pháp", "lettering"),
        "aliases": (("th\u01b0 ph\u00e1p", "vi"),),
        "clip": ("calligraphy writing"),
    },
    {
        "slug": "nail_art",
        "name": "Nail Art",
        "category": "beauty",
        "keywords": ("nail art", "nails", "manicure"),
        "aliases": (),
        "clip": ("nail art design"),
    },
    {
        "slug": "hair",
        "name": "Hair",
        "category": "beauty",
        "keywords": ("hair", "hairstyle", "toc dep", "tóc đẹp", "hair transform"),
        "aliases": (("t\u00f3c", "vi"),),
        "clip": ("hairstyle transformation"),
    },
    {
        "slug": "perfume",
        "name": "Perfume",
        "category": "beauty",
        "keywords": ("perfume", "fragrance", "nuoc hoa", "nước hoa"),
        "aliases": (("n\u01b0\u1edbc hoa", "vi"),),
        "clip": ("perfume bottle fragrance"),
    },
    {
        "slug": "jewelry",
        "name": "Jewelry",
        "category": "fashion",
        "keywords": ("jewelry", "trang suc", "trang sức", "necklace", "ring"),
        "aliases": (("trang s\u1ee9c", "vi"),),
        "clip": ("jewelry accessories"),
    },
    {
        "slug": "watches",
        "name": "Watches",
        "category": "fashion",
        "keywords": ("watches", "dong ho", "đồng hồ", "watch collection"),
        "aliases": (("\u0111\u1ed3ng h\u1ed3", "vi"),),
        "clip": ("luxury watch closeup"),
    },
    {
        "slug": "parenting",
        "name": "Parenting",
        "category": "family",
        "keywords": ("parenting", "nuoi con", "nuôi con", "me bau", "mẹ bầu", "tips me"),
        "aliases": (("nu\u00f4i con", "vi"),),
        "clip": ("parenting with baby"),
    },
    {
        "slug": "wedding_dress",
        "name": "Wedding Dress",
        "category": "wedding",
        "keywords": ("wedding dress", "vay cuoi", "váy cưới", "bridal"),
        "aliases": (("v\u00e1y c\u01b0\u1edbi", "vi"),),
        "clip": ("bridal wedding dress"),
    },
    {
        "slug": "home_cook",
        "name": "Home Cook",
        "category": "food",
        "keywords": ("home cook", "nau an o nha", "nấu ăn ở nhà", "bua com nha"),
        "aliases": (),
        "clip": ("home cooked meal"),
    },
    {
        "slug": "street_interview",
        "name": "Street Interview",
        "category": "viral",
        "keywords": ("street interview", "phong van duong pho", "man on the street"),
        "aliases": (),
        "clip": ("street interview microphone"),
    },
    {
        "slug": "behind_the_scenes",
        "name": "Behind The Scenes",
        "category": "movies",
        "keywords": ("behind the scenes", "bts filming", "hau truong", "hậu trường"),
        "aliases": (("h\u1eadu tr\u01b0\u1eddng", "vi"),),
        "clip": ("behind the scenes filming"),
    },
    {
        "slug": "trailer",
        "name": "Trailer",
        "category": "movies",
        "keywords": ("trailer", "teaser", "official trailer"),
        "aliases": (),
        "clip": ("movie trailer screens"),
    },
    {
        "slug": "shortfilm",
        "name": "Short Film",
        "category": "movies",
        "keywords": ("short film", "phim ngan", "phim ngắn"),
        "aliases": (("phim ng\u1eafn", "vi"),),
        "clip": ("cinematic short film"),
    },
    {
        "slug": "creator_tips",
        "name": "Creator Tips",
        "category": "viral",
        "keywords": ("creator tips", "growth hack", "algorithm tips", "short video tips"),
        "aliases": (),
        "clip": ("social media creator tips"),
    },
    {
        "slug": "youtube",
        "name": "YouTube",
        "category": "career",
        "keywords": ("youtube", "youtuber", "youtube shorts"),
        "aliases": (),
        "clip": ("youtuber recording", "youtube studio"),
    },
    {
        "slug": "content_creator",
        "name": "Content Creator",
        "category": "career",
        "keywords": ("content creator", "creator economy", "kol", "influencer"),
        "aliases": (),
        "clip": ("content creator filming"),
    },
    {
        "slug": "photography_tips",
        "name": "Photography Tips",
        "category": "photography",
        "keywords": ("photography tips", "camera tips", "composition"),
        "aliases": (),
        "clip": ("photography tips tutorial"),
    },
    {
        "slug": "drone",
        "name": "Drone",
        "category": "photography",
        "keywords": ("drone", "fpv", "aerial video", "flycam"),
        "aliases": (),
        "clip": ("drone aerial footage"),
    },
    {
        "slug": "cinematography",
        "name": "Cinematography",
        "category": "movies",
        "keywords": ("cinematography", "cinematic", "color grade"),
        "aliases": (),
        "clip": ("cinematic camera shot"),
    },
    {
        "slug": "editing",
        "name": "Video Editing",
        "category": "technology",
        "keywords": ("video editing", "premiere", "capcut", "davinci", "chinh sua video"),
        "aliases": (),
        "clip": ("video editing timeline"),
    },
    {
        "slug": "after_effects",
        "name": "Motion Design",
        "category": "art",
        "keywords": ("after effects", "motion graphics", "ae edit"),
        "aliases": (),
        "clip": ("motion graphics animation"),
    },
    {
        "slug": "thumbnails",
        "name": "Thumbnails",
        "category": "career",
        "keywords": ("thumbnail", "yt thumbnail"),
        "aliases": (),
        "clip": ("youtube thumbnail design"),
    },
    {
        "slug": "podcast_clips",
        "name": "Podcast Clips",
        "category": "podcast",
        "keywords": ("podcast clip", "shorts from podcast"),
        "aliases": (),
        "clip": ("podcast clip talking heads"),
    },
    {
        "slug": "book_summary",
        "name": "Book Summary",
        "category": "books",
        "keywords": ("book summary", "tom tat sach", "tóm tắt sách"),
        "aliases": (("t\u00f3m t\u1eaft s\u00e1ch", "vi"),),
        "clip": ("book summary notes"),
    },
    {
        "slug": "philosophy",
        "name": "Philosophy",
        "category": "education",
        "keywords": ("philosophy", "triet hoc", "triết học"),
        "aliases": (("tri\u1ebft h\u1ecdc", "vi"),),
        "clip": ("philosophy discussion"),
    },
    {
        "slug": "psychology",
        "name": "Psychology",
        "category": "education",
        "keywords": ("psychology", "tam ly", "tâm lý học", "mental tips"),
        "aliases": (("t\u00e2m l\u00fd", "vi"),),
        "clip": ("psychology concepts"),
    },
    {
        "slug": "mental_health",
        "name": "Mental Health",
        "category": "health",
        "keywords": ("mental health", "suc khoe tinh than", "sức khỏe tinh thần", "anxiety", "depression tips"),
        "aliases": (("tinh th\u1ea7n", "vi"),),
        "clip": ("mental health wellness"),
    },
    {
        "slug": "sleep",
        "name": "Sleep",
        "category": "health",
        "keywords": ("sleep tips", "giac ngu", "giấc ngủ", "insomnia", "ngu ngon"),
        "aliases": (("gi\u1ea5c ng\u1ee7", "vi"),),
        "clip": ("sleep tips bedroom"),
    },
    {
        "slug": "weight_loss",
        "name": "Weight Loss",
        "category": "fitness",
        "keywords": ("weight loss", "giam can", "giảm cân", "fat loss"),
        "aliases": (("gi\u1ea3m c\u00e2n", "vi"),),
        "clip": ("weight loss journey"),
    },
    {
        "slug": "bodybuilding",
        "name": "Bodybuilding",
        "category": "fitness",
        "keywords": ("bodybuilding", "muscle gain", "hypertrophy"),
        "aliases": (),
        "clip": ("bodybuilding gym muscles"),
    },
    {
        "slug": "calisthenics",
        "name": "Calisthenics",
        "category": "fitness",
        "keywords": ("calisthenics", "street workout", "pull up"),
        "aliases": (),
        "clip": ("calisthenics street workout"),
    },
    {
        "slug": "crossfit",
        "name": "CrossFit",
        "category": "fitness",
        "keywords": ("crossfit", "hiit", "functional training"),
        "aliases": (),
        "clip": ("crossfit workout"),
    },
    {
        "slug": "boxing_training",
        "name": "Boxing Training",
        "category": "sports",
        "keywords": ("boxing training", "shadow boxing", "đấm bốc"),
        "aliases": (),
        "clip": ("boxing training gym"),
    },
    {
        "slug": "football_skills",
        "name": "Football Skills",
        "category": "sports",
        "keywords": ("football skills", "soccer freestyle", "ky thuat bong da"),
        "aliases": (),
        "clip": ("soccer freestyle skills"),
    },
    {
        "slug": "f1",
        "name": "Formula 1",
        "category": "sports",
        "keywords": ("formula 1", "f1", "grand prix"),
        "aliases": (),
        "clip": ("formula 1 race car"),
    },
    {
        "slug": "esports_valorant",
        "name": "Valorant Esports",
        "category": "gaming",
        "keywords": ("valorant champions", "vct"),
        "aliases": (),
        "clip": ("valorant esports stage"),
    },
    {
        "slug": "chess",
        "name": "Chess",
        "category": "education",
        "keywords": ("chess", "co vua", "cờ vua", "checkmate"),
        "aliases": (("c\u1edd vua", "vi"),),
        "clip": ("chess board game"),
    },
    {
        "slug": "boardgames",
        "name": "Board Games",
        "category": "lifestyle",
        "keywords": ("board game", "boardgame", "tro choi ban"),
        "aliases": (),
        "clip": ("board game night"),
    },
    {
        "slug": "collectibles",
        "name": "Collectibles",
        "category": "lifestyle",
        "keywords": ("collectibles", "figure", "pop mart", "blind box", "mo mo"),
        "aliases": (),
        "clip": ("collectible figures"),
    },
    {
        "slug": "lego",
        "name": "LEGO",
        "category": "diy",
        "keywords": ("lego", "lego build"),
        "aliases": (),
        "clip": ("lego building bricks"),
    },
    {
        "slug": "origami",
        "name": "Origami",
        "category": "diy",
        "keywords": ("origami", "gap giay", "gấp giấy"),
        "aliases": (("g\u1ea5p gi\u1ea5y", "vi"),),
        "clip": ("origami paper folding"),
    },
    {
        "slug": "sewing",
        "name": "Sewing",
        "category": "diy",
        "keywords": ("sewing", "may va", "may vá", "diy clothes"),
        "aliases": (("may v\u00e1", "vi"),),
        "clip": ("sewing machine clothes"),
    },
    {
        "slug": "knitting",
        "name": "Knitting",
        "category": "diy",
        "keywords": ("knitting", "crochet", "moc"),
        "aliases": (),
        "clip": ("knitting yarn crochet"),
    },
    {
        "slug": "pottery",
        "name": "Pottery",
        "category": "art",
        "keywords": ("pottery", "gom", "ceramic"),
        "aliases": (),
        "clip": ("pottery wheel ceramics"),
    },
    {
        "slug": "tattoo",
        "name": "Tattoo",
        "category": "art",
        "keywords": ("tattoo", "xam", "xăm", "ink tattoo"),
        "aliases": (("x\u0103m", "vi"),),
        "clip": ("tattoo artist inking"),
    },
    {
        "slug": "piercing",
        "name": "Piercing",
        "category": "beauty",
        "keywords": ("piercing", "ear piercing"),
        "aliases": (),
        "clip": ("ear piercing jewelry"),
    },
    {
        "slug": "barber",
        "name": "Barber",
        "category": "beauty",
        "keywords": ("barber", "fade haircut", "cat toc nam", "cắt tóc nam"),
        "aliases": (),
        "clip": ("barber haircut fade"),
    },
    {
        "slug": "salon",
        "name": "Salon",
        "category": "beauty",
        "keywords": ("salon", "lam toc", "làm tóc", "hair salon"),
        "aliases": (("l\u00e0m t\u00f3c", "vi"),),
        "clip": ("hair salon styling"),
    },
    {
        "slug": "spa",
        "name": "Spa",
        "category": "health",
        "keywords": ("spa", "massage", "facial spa"),
        "aliases": (),
        "clip": ("spa massage relaxation"),
    },
    {
        "slug": "dental",
        "name": "Dental",
        "category": "health",
        "keywords": ("dental", "nha khoa", "braces", "rang"),
        "aliases": (),
        "clip": ("dental clinic care"),
    },
    {
        "slug": "medical",
        "name": "Medical",
        "category": "health",
        "keywords": ("medical", "bac si", "bác sĩ", "hospital tips"),
        "aliases": (("b\u00e1c s\u0129", "vi"),),
        "clip": ("medical doctor advice"),
    },
    {
        "slug": "first_aid",
        "name": "First Aid",
        "category": "health",
        "keywords": ("first aid", "so cuu", "sơ cứu"),
        "aliases": (("s\u01a1 c\u1ee9u", "vi"),),
        "clip": ("first aid emergency"),
    },
    {
        "slug": "pregnancy",
        "name": "Pregnancy",
        "category": "family",
        "keywords": ("pregnancy", "bau", "bầu", "mang thai", "prenatal"),
        "aliases": (("mang thai", "vi"),),
        "clip": ("pregnancy maternity"),
    },
    {
        "slug": "newborn",
        "name": "Newborn",
        "category": "kids",
        "keywords": ("newborn", "so sinh", "sơ sinh", "baby care"),
        "aliases": (("s\u01a1 sinh", "vi"),),
        "clip": ("newborn baby care"),
    },
    {
        "slug": "toys",
        "name": "Toys",
        "category": "kids",
        "keywords": ("toys", "do choi", "đồ chơi", "lego kids"),
        "aliases": (("\u0111\u1ed3 ch\u01a1i", "vi"),),
        "clip": ("kids toys"),
    },
    {
        "slug": "cartoon",
        "name": "Cartoon",
        "category": "kids",
        "keywords": ("cartoon", "hoat hinh tre em", "kids cartoon"),
        "aliases": (),
        "clip": ("kids cartoon animation"),
    },
    {
        "slug": "disney",
        "name": "Disney",
        "category": "movies",
        "keywords": ("disney", "pixar", "disney plus"),
        "aliases": (),
        "clip": ("disney animation"),
    },
    {
        "slug": "marvel",
        "name": "Marvel",
        "category": "movies",
        "keywords": ("marvel", "avengers", "mcu", "spiderman"),
        "aliases": (),
        "clip": ("marvel superhero scene"),
    },
    {
        "slug": "dc_comics",
        "name": "DC",
        "category": "movies",
        "keywords": ("dc comics", "batman", "superman", "joker"),
        "aliases": (),
        "clip": ("dc superhero batman"),
    },
    {
        "slug": "star_wars",
        "name": "Star Wars",
        "category": "scifi",
        "keywords": ("star wars", "jedi", "lightsaber"),
        "aliases": (),
        "clip": ("star wars scene"),
    },
    {
        "slug": "harry_potter",
        "name": "Harry Potter",
        "category": "movies",
        "keywords": ("harry potter", "hogwarts", "wizarding"),
        "aliases": (),
        "clip": ("harry potter magical"),
    },
    {
        "slug": "fantasy",
        "name": "Fantasy",
        "category": "movies",
        "keywords": ("fantasy", "magic world", "kiem hiep", "kiếm hiệp"),
        "aliases": (("ki\u1ebfm hi\u1ec7p", "vi"),),
        "clip": ("fantasy adventure world"),
    },
    {
        "slug": "mythology",
        "name": "Mythology",
        "category": "history",
        "keywords": ("mythology", "than thoai", "thần thoại", "greek myth"),
        "aliases": (("th\u1ea7n tho\u1ea1i", "vi"),),
        "clip": ("mythology gods story"),
    },
    {
        "slug": "war_history",
        "name": "War History",
        "category": "history",
        "keywords": ("war history", "chien tranh", "chiến tranh", "ww2"),
        "aliases": (("chi\u1ebfn tranh", "vi"),),
        "clip": ("war history documentary"),
    },
    {
        "slug": "archaeology",
        "name": "Archaeology",
        "category": "history",
        "keywords": ("archaeology", "khao co", "khảo cổ"),
        "aliases": (("kh\u1ea3o c\u1ed5", "vi"),),
        "clip": ("archaeology excavation"),
    },
    {
        "slug": "space",
        "name": "Space",
        "category": "science",
        "keywords": ("space", "nasa", "astronomy", "vu tru", "vũ trụ", "galaxy"),
        "aliases": (("v\u0169 tr\u1ee5", "vi"),),
        "clip": ("outer space galaxy"),
    },
    {
        "slug": "physics",
        "name": "Physics",
        "category": "science",
        "keywords": ("physics", "vat ly", "vật lý"),
        "aliases": (("v\u1eadt l\u00fd", "vi"),),
        "clip": ("physics experiment"),
    },
    {
        "slug": "chemistry",
        "name": "Chemistry",
        "category": "science",
        "keywords": ("chemistry", "hoa hoc", "hóa học"),
        "aliases": (("h\u00f3a h\u1ecdc", "vi"),),
        "clip": ("chemistry lab experiment"),
    },
    {
        "slug": "biology",
        "name": "Biology",
        "category": "science",
        "keywords": ("biology", "sinh hoc", "sinh học"),
        "aliases": (("sinh h\u1ecdc", "vi"),),
        "clip": ("biology science"),
    },
    {
        "slug": "environment",
        "name": "Environment",
        "category": "nature",
        "keywords": ("environment", "moi truong", "môi trường", "climate", "recycle"),
        "aliases": (("m\u00f4i tr\u01b0\u1eddng", "vi"),),
        "clip": ("environment nature climate"),
    },
    {
        "slug": "wildlife",
        "name": "Wildlife",
        "category": "nature",
        "keywords": ("wildlife", "dong vat hoang da", "safari", "wild animals"),
        "aliases": (),
        "clip": ("wildlife animals nature"),
    },
    {
        "slug": "ocean",
        "name": "Ocean",
        "category": "nature",
        "keywords": ("ocean", "bien sau", "underwater", "coral reef"),
        "aliases": (),
        "clip": ("underwater ocean reef"),
    },
    {
        "slug": "hiking",
        "name": "Hiking",
        "category": "travel",
        "keywords": ("hiking", "trekking", "leo nui", "leo núi"),
        "aliases": (("leo n\u00fai", "vi"),),
        "clip": ("hiking mountain trail"),
    },
    {
        "slug": "backpacking",
        "name": "Backpacking",
        "category": "travel",
        "keywords": ("backpacking", "phuot", "phượt", "budget travel"),
        "aliases": (("ph\u01b0\u1ee3t", "vi"),),
        "clip": ("backpacking travel"),
    },
    {
        "slug": "luxury_travel",
        "name": "Luxury Travel",
        "category": "travel",
        "keywords": ("luxury travel", "resort", "5 star hotel"),
        "aliases": (),
        "clip": ("luxury resort travel"),
    },
    {
        "slug": "hotel",
        "name": "Hotel",
        "category": "travel",
        "keywords": ("hotel", "khach san", "khách sạn", "hotel tour"),
        "aliases": (("kh\u00e1ch s\u1ea1n", "vi"),),
        "clip": ("hotel room tour"),
    },
    {
        "slug": "airport",
        "name": "Airport",
        "category": "travel",
        "keywords": ("airport", "san bay", "sân bay", "flight"),
        "aliases": (("s\u00e2n bay", "vi"),),
        "clip": ("airport travel"),
    },
    {
        "slug": "train_travel",
        "name": "Train Travel",
        "category": "travel",
        "keywords": ("train travel", "tau hoa", "tàu hỏa"),
        "aliases": (("t\u00e0u h\u1ecfa", "vi"),),
        "clip": ("train journey travel"),
    },
    {
        "slug": "street_photography",
        "name": "Street Photography",
        "category": "photography",
        "keywords": ("street photography", "streetphoto"),
        "aliases": (),
        "clip": ("street photography candid"),
    },
    {
        "slug": "portrait",
        "name": "Portrait",
        "category": "photography",
        "keywords": ("portrait", "chan dung", "chân dung", "portrait photography"),
        "aliases": (("ch\u00e2n dung", "vi"),),
        "clip": ("portrait photography"),
    },
    {
        "slug": "wedding_photo",
        "name": "Wedding Photography",
        "category": "wedding",
        "keywords": ("wedding photography", "chup cuoi", "chụp cưới"),
        "aliases": (("ch\u1ee5p c\u01b0\u1edbi", "vi"),),
        "clip": ("wedding photography couple"),
    },
    {
        "slug": "real_estate_tour",
        "name": "Property Tour",
        "category": "realestate",
        "keywords": ("house tour", "apartment tour", "nha dep", "căn hộ đẹp"),
        "aliases": (),
        "clip": ("house tour interior"),
    },
    {
        "slug": "investing",
        "name": "Investing",
        "category": "finance",
        "keywords": ("investing", "dau tu", "đầu tư", "portfolio"),
        "aliases": (("\u0111\u1ea7u t\u01b0", "vi"),),
        "clip": ("investing finance charts"),
    },
    {
        "slug": "stock_market",
        "name": "Stock Market",
        "category": "finance",
        "keywords": ("stock market", "chung khoan", "chứng khoán", "trading"),
        "aliases": (("ch\u1ee9ng kho\u00e1n", "vi"),),
        "clip": ("stock market trading"),
    },
    {
        "slug": "saving_money",
        "name": "Saving Money",
        "category": "finance",
        "keywords": ("saving money", "tiet kiem", "tiết kiệm", "frugal"),
        "aliases": (("ti\u1ebft ki\u1ec7m", "vi"),),
        "clip": ("saving money tips"),
    },
    {
        "slug": "tax",
        "name": "Tax",
        "category": "finance",
        "keywords": ("tax tips", "thue", "thuế", "personal finance tax"),
        "aliases": (("thu\u1ebf", "vi"),),
        "clip": ("tax finance documents"),
    },
    {
        "slug": "startup",
        "name": "Startup",
        "category": "career",
        "keywords": ("startup", "founder", "entrepreneur", "khoi nghiep", "khởi nghiệp"),
        "aliases": (("kh\u1edfi nghi\u1ec7p", "vi"),),
        "clip": ("startup entrepreneurs"),
    },
    {
        "slug": "marketing",
        "name": "Marketing",
        "category": "career",
        "keywords": ("marketing", "digital marketing", "ads", "seo"),
        "aliases": (),
        "clip": ("digital marketing ads"),
    },
    {
        "slug": "sales",
        "name": "Sales",
        "category": "career",
        "keywords": ("sales tips", "ban hang", "bán hàng", "closing deal"),
        "aliases": (("b\u00e1n h\u00e0ng", "vi"),),
        "clip": ("sales business meeting"),
    },
    {
        "slug": "customer_service",
        "name": "Customer Service",
        "category": "career",
        "keywords": ("customer service", "cham soc khach", "cs khach hang"),
        "aliases": (),
        "clip": ("customer service support"),
    },
    {
        "slug": "office_life",
        "name": "Office Life",
        "category": "career",
        "keywords": ("office life", "van phong", "cuộc sống văn phòng", "9to5"),
        "aliases": (),
        "clip": ("office workplace life"),
    },
    {
        "slug": "freelancer",
        "name": "Freelancer",
        "category": "career",
        "keywords": ("freelancer", "freelance", "upwork", "fiverr"),
        "aliases": (),
        "clip": ("freelancer working laptop"),
    },
    {
        "slug": "teacher",
        "name": "Teacher",
        "category": "education",
        "keywords": ("teacher", "giao vien", "giáo viên", "teaching tips"),
        "aliases": (("gi\u00e1o vi\u00ean", "vi"),),
        "clip": ("teacher in classroom"),
    },
    {
        "slug": "student_life",
        "name": "Student Life",
        "category": "education",
        "keywords": ("student life", "doi sinh vien", "đời sinh viên", "campus life"),
        "aliases": (("sinh vi\u00ean", "vi"),),
        "clip": ("student campus life"),
    },
    {
        "slug": "scholarship",
        "name": "Scholarship",
        "category": "education",
        "keywords": ("scholarship", "hoc bong", "học bổng"),
        "aliases": (("h\u1ecdc b\u1ed5ng", "vi"),),
        "clip": ("scholarship education"),
    },
    {
        "slug": "pho",
        "name": "Pho",
        "category": "food",
        "keywords": ("pho", "phở", "pho bo", "phở bò"),
        "aliases": (("ph\u1edf", "vi"),),
        "clip": ("vietnamese pho bowl"),
    },
    {
        "slug": "banh_mi",
        "name": "Banh Mi",
        "category": "food",
        "keywords": ("banh mi", "bánh mì"),
        "aliases": (("b\u00e1nh m\u00ec", "vi"),),
        "clip": ("vietnamese banh mi"),
    },
    {
        "slug": "bun_bo",
        "name": "Bun Bo",
        "category": "food",
        "keywords": ("bun bo", "bún bò", "bun bo hue"),
        "aliases": (("b\u00fan b\u00f2", "vi"),),
        "clip": ("bun bo hue bowl"),
    },
    {
        "slug": "com_tam",
        "name": "Com Tam",
        "category": "food",
        "keywords": ("com tam", "cơm tấm"),
        "aliases": (("c\u01a1m t\u1ea5m", "vi"),),
        "clip": ("com tam broken rice"),
    },
    {
        "slug": "bun_cha",
        "name": "Bun Cha",
        "category": "food",
        "keywords": ("bun cha", "bún chả"),
        "aliases": (("b\u00fan ch\u1ea3", "vi"),),
        "clip": ("bun cha hanoi"),
    },
    {
        "slug": "banh_xeo",
        "name": "Banh Xeo",
        "category": "food",
        "keywords": ("banh xeo", "bánh xèo"),
        "aliases": (("b\u00e1nh x\u00e8o", "vi"),),
        "clip": ("vietnamese banh xeo"),
    },
    {
        "slug": "goi_cuon",
        "name": "Goi Cuon",
        "category": "food",
        "keywords": ("goi cuon", "gỏi cuốn", "spring rolls"),
        "aliases": (("g\u1ecfi cu\u1ed1n", "vi"),),
        "clip": ("fresh spring rolls"),
    },
    {
        "slug": "banh_chung",
        "name": "Banh Chung",
        "category": "food",
        "keywords": ("banh chung", "bánh chưng", "banh tet"),
        "aliases": (("b\u00e1nh ch\u01b0ng", "vi"),),
        "clip": ("banh chung tet food"),
    },
    {
        "slug": "che",
        "name": "Che Dessert",
        "category": "food",
        "keywords": ("che ba mau", "chè", "che thai"),
        "aliases": (("ch\u00e8", "vi"),),
        "clip": ("vietnamese che dessert"),
    },
    {
        "slug": "hu_tieu",
        "name": "Hu Tieu",
        "category": "food",
        "keywords": ("hu tieu", "hủ tiếu"),
        "aliases": (("h\u1ee7 ti\u1ebfu", "vi"),),
        "clip": ("hu tieu noodle soup"),
    },
    {
        "slug": "mi_quang",
        "name": "Mi Quang",
        "category": "food",
        "keywords": ("mi quang", "mì quảng"),
        "aliases": (("m\u00ec qu\u1ea3ng", "vi"),),
        "clip": ("mi quang noodles"),
    },
    {
        "slug": "cao_lau",
        "name": "Cao Lau",
        "category": "food",
        "keywords": ("cao lau", "cao lầu"),
        "aliases": (("cao l\u1ea7u", "vi"),),
        "clip": ("cao lau hoi an"),
    },
    {
        "slug": "oc",
        "name": "Oc Seafood",
        "category": "food",
        "keywords": ("oc", "ốc", "an oc", "ốc hút"),
        "aliases": (("\u1ed1c", "vi"),),
        "clip": ("vietnamese snails oc"),
    },
    {
        "slug": "bun_dau",
        "name": "Bun Dau",
        "category": "food",
        "keywords": ("bun dau", "bún đậu", "bun dau mam tom"),
        "aliases": (("b\u00fan \u0111\u1eadu", "vi"),),
        "clip": ("bun dau mam tom"),
    },
    {
        "slug": "dimsum",
        "name": "Dim Sum",
        "category": "food",
        "keywords": ("dimsum", "dim sum", "ha cao", "há cảo"),
        "aliases": (),
        "clip": ("dim sum dumplings"),
    },
    {
        "slug": "ramen",
        "name": "Ramen",
        "category": "food",
        "keywords": ("ramen", "tonkotsu"),
        "aliases": (),
        "clip": ("japanese ramen bowl"),
    },
    {
        "slug": "sushi",
        "name": "Sushi",
        "category": "food",
        "keywords": ("sushi", "sashimi", "nigiri"),
        "aliases": (),
        "clip": ("sushi platter"),
    },
    {
        "slug": "pizza",
        "name": "Pizza",
        "category": "food",
        "keywords": ("pizza", "pepperoni pizza"),
        "aliases": (),
        "clip": ("pizza slice"),
    },
    {
        "slug": "burger",
        "name": "Burger",
        "category": "food",
        "keywords": ("burger", "hamburger", "cheeseburger"),
        "aliases": (),
        "clip": ("hamburger burger"),
    },
    {
        "slug": "fried_chicken",
        "name": "Fried Chicken",
        "category": "food",
        "keywords": ("fried chicken", "ga ran", "gà rán", "kfc style"),
        "aliases": (("g\u00e0 r\u00e1n", "vi"),),
        "clip": ("fried chicken"),
    },
    {
        "slug": "bbq_korea",
        "name": "Korean BBQ",
        "category": "food",
        "keywords": ("korean bbq", "bbq han", "thit nuong han"),
        "aliases": (),
        "clip": ("korean bbq grill"),
    },
    {
        "slug": "hotpot_china",
        "name": "Chinese Hotpot",
        "category": "food",
        "keywords": ("chinese hotpot", "malatang", "haidilao"),
        "aliases": (),
        "clip": ("chinese hotpot"),
    },
    {
        "slug": "icecream",
        "name": "Ice Cream",
        "category": "food",
        "keywords": ("ice cream", "kem", "gelato", "sundae"),
        "aliases": (("kem", "vi"),),
        "clip": ("ice cream dessert"),
    },
    {
        "slug": "chocolate",
        "name": "Chocolate",
        "category": "food",
        "keywords": ("chocolate", "socola", "cacao"),
        "aliases": (),
        "clip": ("chocolate dessert"),
    },
    {
        "slug": "tea",
        "name": "Tea",
        "category": "food",
        "keywords": ("tea", "tra", "trà", "matcha", "tra xanh"),
        "aliases": (("tr\u00e0", "vi"),),
        "clip": ("tea ceremony cup"),
    },
    {
        "slug": "matcha",
        "name": "Matcha",
        "category": "food",
        "keywords": ("matcha", "matcha latte"),
        "aliases": (),
        "clip": ("matcha green tea latte"),
    },
    {
        "slug": "smoothie",
        "name": "Smoothie",
        "category": "food",
        "keywords": ("smoothie", "juice", "nuoc ep", "nước ép"),
        "aliases": (("n\u01b0\u1edbc \u00e9p", "vi"),),
        "clip": ("fruit smoothie"),
    },
    {
        "slug": "one_piece",
        "name": "One Piece",
        "category": "anime",
        "keywords": ("one piece", "luffy", "zoro", "onepiece"),
        "aliases": (),
        "clip": ("one piece anime"),
    },
    {
        "slug": "naruto",
        "name": "Naruto",
        "category": "anime",
        "keywords": ("naruto", "sasuke", "boruto"),
        "aliases": (),
        "clip": ("naruto anime ninja"),
    },
    {
        "slug": "demon_slayer",
        "name": "Demon Slayer",
        "category": "anime",
        "keywords": ("demon slayer", "kimetsu", "tanjiro"),
        "aliases": (),
        "clip": ("demon slayer anime"),
    },
    {
        "slug": "jujutsu_kaisen",
        "name": "Jujutsu Kaisen",
        "category": "anime",
        "keywords": ("jujutsu kaisen", "jjk", "gojo"),
        "aliases": (),
        "clip": ("jujutsu kaisen anime"),
    },
    {
        "slug": "aot",
        "name": "Attack on Titan",
        "category": "anime",
        "keywords": ("attack on titan", "aot", "shingeki"),
        "aliases": (),
        "clip": ("attack on titan anime"),
    },
    {
        "slug": "dragon_ball",
        "name": "Dragon Ball",
        "category": "anime",
        "keywords": ("dragon ball", "goku", "dbz"),
        "aliases": (),
        "clip": ("dragon ball anime"),
    },
    {
        "slug": "pokemon",
        "name": "Pokemon",
        "category": "anime",
        "keywords": ("pokemon", "pokémon", "pikachu"),
        "aliases": (),
        "clip": ("pokemon anime"),
    },
    {
        "slug": "studio_ghibli",
        "name": "Studio Ghibli",
        "category": "anime",
        "keywords": ("ghibli", "totoro", "spirited away"),
        "aliases": (),
        "clip": ("studio ghibli style"),
    },
    {
        "slug": "honkai",
        "name": "Honkai",
        "category": "gaming",
        "keywords": ("honkai", "honkai star rail", "hsr"),
        "aliases": (),
        "clip": ("honkai star rail"),
    },
    {
        "slug": "zenless",
        "name": "Zenless Zone Zero",
        "category": "gaming",
        "keywords": ("zenless", "zzz game"),
        "aliases": (),
        "clip": ("zenless zone zero"),
    },
    {
        "slug": "lol_wild_rift",
        "name": "Wild Rift",
        "category": "gaming",
        "keywords": ("wild rift", "lol mobile"),
        "aliases": (),
        "clip": ("league wild rift"),
    },
    {
        "slug": "cod_mobile",
        "name": "COD Mobile",
        "category": "gaming",
        "keywords": ("cod mobile", "call of duty mobile"),
        "aliases": (),
        "clip": ("cod mobile gameplay"),
    },
    {
        "slug": "clash_royale",
        "name": "Clash Royale",
        "category": "gaming",
        "keywords": ("clash royale", "clash of clans"),
        "aliases": (),
        "clip": ("clash royale gameplay"),
    },
    {
        "slug": "among_us",
        "name": "Among Us",
        "category": "gaming",
        "keywords": ("among us", "imposter"),
        "aliases": (),
        "clip": ("among us gameplay"),
    },
    {
        "slug": "minecraft_build",
        "name": "Minecraft Build",
        "category": "gaming",
        "keywords": ("minecraft build", "minecraft house", "redstone"),
        "aliases": (),
        "clip": ("minecraft building"),
    },
    {
        "slug": "indie_music",
        "name": "Indie Music",
        "category": "music",
        "keywords": ("indie music", "indie song", "nhac indie"),
        "aliases": (),
        "clip": ("indie music performance"),
    },
    {
        "slug": "acoustic",
        "name": "Acoustic",
        "category": "music",
        "keywords": ("acoustic", "acoustic cover", "dan guitar acoustic"),
        "aliases": (),
        "clip": ("acoustic guitar singing"),
    },
    {
        "slug": "rnb",
        "name": "R&B",
        "category": "music",
        "keywords": ("r&b", "rnb", "soul music"),
        "aliases": (),
        "clip": ("rnb soul performance"),
    },
    {
        "slug": "usuk",
        "name": "US-UK Pop",
        "category": "music",
        "keywords": ("usuk", "us-uk", "western pop", "billboard"),
        "aliases": (),
        "clip": ("western pop music video"),
    },
    {
        "slug": "latin",
        "name": "Latin Music",
        "category": "music",
        "keywords": ("latin music", "reggaeton", "salsa"),
        "aliases": (),
        "clip": ("latin music dance"),
    },
    {
        "slug": "vietnamese_rap",
        "name": "V-Rap",
        "category": "music",
        "keywords": ("vrap", "rap viet", "vietnamese rap"),
        "aliases": (),
        "clip": ("vietnamese rap freestyle"),
    },
    {
        "slug": "bolero",
        "name": "Bolero",
        "category": "music",
        "keywords": ("bolero", "nhac bolero", "nhạc trữ tình"),
        "aliases": (),
        "clip": ("bolero emotional singing"),
    },
    {
        "slug": "cai_luong",
        "name": "Cai Luong",
        "category": "music",
        "keywords": ("cai luong", "cải lương"),
        "aliases": (("c\u1ea3i l\u01b0\u01a1ng", "vi"),),
        "clip": ("cai luong traditional"),
    },
    {
        "slug": "cheo",
        "name": "Cheo",
        "category": "music",
        "keywords": ("cheo", "chèo"),
        "aliases": (("ch\u00e8o", "vi"),),
        "clip": ("cheo traditional theater"),
    },
    {
        "slug": "supercar",
        "name": "Supercar",
        "category": "automotive",
        "keywords": ("supercar", "lamborghini", "ferrari", "mclaren"),
        "aliases": (),
        "clip": ("supercar sports car"),
    },
    {
        "slug": "jdm",
        "name": "JDM",
        "category": "automotive",
        "keywords": ("jdm", "toyota supra", "nissan gtr", "honda civic type r"),
        "aliases": (),
        "clip": ("jdm car modification"),
    },
    {
        "slug": "car_mod",
        "name": "Car Mod",
        "category": "automotive",
        "keywords": ("car mod", "car modification", "stance", "wrap"),
        "aliases": (),
        "clip": ("modified car wrap"),
    },
    {
        "slug": "ev_review",
        "name": "EV Review",
        "category": "automotive",
        "keywords": ("ev review", "vinfast review", "tesla review"),
        "aliases": (),
        "clip": ("electric vehicle review"),
    },
    {
        "slug": "gadget",
        "name": "Gadget",
        "category": "technology",
        "keywords": ("gadget", "tech gadget", "must have gadget"),
        "aliases": (),
        "clip": ("tech gadgets desk"),
    },
    {
        "slug": "camera_gear",
        "name": "Camera Gear",
        "category": "photography",
        "keywords": ("camera gear", "sony a7", "canon r", "gopro"),
        "aliases": (),
        "clip": ("camera gear photography"),
    },
    {
        "slug": "headphones",
        "name": "Headphones",
        "category": "technology",
        "keywords": ("headphones", "earbuds", "airpods", "tai nghe"),
        "aliases": (("tai nghe", "vi"),),
        "clip": ("headphones earbuds"),
    },
    {
        "slug": "smart_home",
        "name": "Smart Home",
        "category": "technology",
        "keywords": ("smart home", "iot", "alexa", "nha thong minh"),
        "aliases": (),
        "clip": ("smart home devices"),
    },
    {
        "slug": "nsfw",
        "name": "NSFW",
        "category": None,
        "keywords": ("nsfw", "adult only", "18+", "not safe for work"),
        "aliases": (),
        "clip": ("explicit nudity pornographic adult content", "nsfw sexual content in video", "adult explicit material not safe for work"),
    },
    {
        "slug": "explicit",
        "name": "Explicit Content",
        "category": None,
        "keywords": ("explicit", "explicit content", "18 plus", "mature explicit"),
        "aliases": (),
        "clip": ("explicit sexual content in video", "explicit nudity scene", "adult explicit sexual act"),
    },
    {
        "slug": "porn",
        "name": "Pornography",
        "category": None,
        "keywords": ("porn", "pornography", "xxx video", "hardcore"),
        "aliases": (),
        "clip": ("pornographic video scene", "hardcore pornography", "adult porn video"),
    },
    {
        "slug": "adult_content",
        "name": "Adult Content",
        "category": None,
        "keywords": ("adult content", "adult video", "mature content", "adults only"),
        "aliases": (),
        "clip": ("adult only mature sexual content", "restricted adult video", "mature audience sexual content"),
    },
    {
        "slug": "adult",
        "name": "Adult",
        "category": None,
        "keywords": ("adult", "adult material", "adult scene"),
        "aliases": (),
        "clip": ("adult sexual content", "adult only video", "mature adult scene"),
    },
    {
        "slug": "nudity",
        "name": "Nudity",
        "category": None,
        "keywords": ("nudity", "nude", "naked", "topless", "no clothes"),
        "aliases": (),
        "clip": ("full frontal nudity", "naked person without clothes", "topless nude body"),
    },
    {
        "slug": "lingerie",
        "name": "Lingerie",
        "category": None,
        "keywords": ("lingerie", "underwear model", "sexy lingerie"),
        "aliases": (),
        "clip": ("person in lingerie underwear", "sexy lingerie photoshoot", "revealing lingerie"),
    },
    {
        "slug": "seductive",
        "name": "Seductive",
        "category": None,
        "keywords": ("seductive", "provocative pose", "sensual"),
        "aliases": (),
        "clip": ("seductive provocative pose", "sensual adult pose", "provocative sexual pose"),
    },
    {
        "slug": "kissing",
        "name": "Kissing",
        "category": None,
        "keywords": ("kissing", "make out", "passionate kiss"),
        "aliases": (),
        "clip": ("passionate kissing couple", "people kissing intimately", "romantic kiss closeup"),
    },
    {
        "slug": "violence",
        "name": "Violence",
        "category": None,
        "keywords": ("violence", "violent", "graphic violence", "assault"),
        "aliases": (),
        "clip": ("graphic violence assault", "violent fight beating", "people fighting violently"),
    },
    {
        "slug": "gore",
        "name": "Gore",
        "category": None,
        "keywords": ("gore", "bloodbath", "graphic gore", "disturbing gore"),
        "aliases": (),
        "clip": ("graphic gore blood injury", "bloody gore violent injury", "disturbing gore scene"),
    },
    {
        "slug": "weapon",
        "name": "Weapon",
        "category": None,
        "keywords": ("weapon", "armed", "weapon threat", "deadly weapon"),
        "aliases": (),
        "clip": ("person holding weapon threatening", "knife or gun weapon violence", "armed person with weapon"),
    },
    {
        "slug": "guns",
        "name": "Guns",
        "category": None,
        "keywords": ("guns", "gun", "firearm", "shooting", "pistol", "rifle"),
        "aliases": (),
        "clip": ("person holding gun firearm", "gun shooting violence", "firearm pointed at camera"),
    },
    {
        "slug": "blood",
        "name": "Blood",
        "category": None,
        "keywords": ("blood", "bloody", "bleeding", "blood injury"),
        "aliases": (),
        "clip": ("blood injury wound", "bloody violent scene", "bleeding graphic wound"),
    },
]

LEXICON: dict[str, tuple[str, ...]] = {row['slug']: tuple(row['keywords']) for row in TAG_ROWS}
CLIP_TAG_PROMPTS: dict[str, tuple[str, ...]] = {row['slug']: tuple(row['clip']) for row in TAG_ROWS}
TAG_NAMES: dict[str, str] = {row['slug']: row['name'] for row in TAG_ROWS}

# count=361

