export const DEFAULT_AVATAR_URL = '/images/users/default-avatar.jpeg'

export const SEARCH_DEBOUNCE_MS = 300

/** Max length stored/sent for search queries (defense in depth). */
export const SEARCH_QUERY_MAX_LENGTH = 200

/**
 * Canonical search text: trim, collapse spaces, strip # / controls / markup,
 * lowercase, length cap. Keeps Vietnamese accents.
 */
export function normalizeSearchQuery(raw) {
  let text = String(raw ?? '')
  // Strip control chars; map newlines/tabs to space
  text = text.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, '')
  text = text.replace(/[\n\r\t]+/g, ' ')
  // Strip characters that are useless in search and risky when reflected in HTML/URLs
  text = text.replace(/[<>"'`]/g, '')
  text = text.trim().replace(/\s+/g, ' ')
  if (text.startsWith('#')) {
    text = text.slice(1).trim()
  }
  if (text.length > SEARCH_QUERY_MAX_LENGTH) {
    text = text.slice(0, SEARCH_QUERY_MAX_LENGTH).trim()
  }
  return text.toLocaleLowerCase('vi')
}

export function buildProfileHref(username) {
  const raw = String(username ?? '')
    .trim()
    .replace(/^@/, '')
  return raw ? `/@${encodeURIComponent(raw)}` : '/'
}

export function buildHashtagHref(tag) {
  const raw = String(tag ?? '')
    .trim()
    .replace(/^#/, '')
  return raw ? `/tag/${encodeURIComponent(raw)}` : '/explore'
}

export function buildVideoHref(publicId) {
  const id = String(publicId ?? '').trim()
  return id ? `/?v=${encodeURIComponent(id)}` : '/'
}

/** Gợi ý có liên quan tới chuỗi đang gõ (substring, không phân biệt hoa thường). */
export function suggestKeywordMatchesQuery(keyword, rawQuery) {
  const k = normalizeSearchQuery(keyword).toLowerCase()
  const q = normalizeSearchQuery(rawQuery).toLowerCase()
  if (!k || !q) return false
  return k.includes(q)
}

export function buildSearchResultsHref(rawQuery) {
  const q = normalizeSearchQuery(rawQuery)
  return q ? `/search?q=${encodeURIComponent(q)}` : '/search'
}

function looksLikeAutoGeneratedTitle(value) {
  const text = String(value ?? '').trim()
  if (!text) return true
  if (/snaptik\.|tiktokdownloader|\.mp4$|\.mov$|\.webm$/i.test(text)) return true
  if (/^[\w.-]+\.(mp4|mov|webm)$/i.test(text)) return true
  return false
}

/** Caption ưu tiên mô tả video (không dùng tên file upload). */
export function resolveVideoSearchCaption(video) {
  const description = String(video?.description ?? '').trim()
  if (description) return description
  const title = String(video?.title ?? '').trim()
  if (title && !looksLikeAutoGeneratedTitle(title)) return title
  return 'Xem video'
}

export function emptySuggestPayload() {
  return {
    trending: [],
    users: [],
    hashtags: [],
    videos: [],
  }
}
