export const DEFAULT_AVATAR_URL = '/images/users/default-avatar.jpeg'

export const SEARCH_DEBOUNCE_MS = 300

export function normalizeSearchQuery(raw) {
  const trimmed = String(raw ?? '').trim().replace(/\s+/g, ' ')
  if (trimmed.startsWith('#')) {
    return trimmed.slice(1).trim()
  }
  return trimmed
}

export function buildProfileHref(username) {
  const raw = String(username ?? '')
    .trim()
    .replace(/^@/, '')
  return raw ? `/@${encodeURIComponent(raw)}` : '/foryou'
}

export function buildHashtagHref(tag) {
  const raw = String(tag ?? '')
    .trim()
    .replace(/^#/, '')
  return raw ? `/tag/${encodeURIComponent(raw)}` : '/explore'
}

export function buildVideoHref(publicId) {
  const id = String(publicId ?? '').trim()
  return id ? `/foryou?v=${encodeURIComponent(id)}` : '/foryou'
}

function looksLikeAutoGeneratedTitle(value) {
  const text = String(value ?? '').trim()
  if (!text) return true
  if (/snaptik\.|tiktokdownloader|\.mp4$|\.mov$|\.webm$/i.test(text)) return true
  if (/^[\w.-]+\.(mp4|mov|webm)$/i.test(text)) return true
  return false
}

/** Caption ưu tiên mô tả video (không dùng tên file upload). */
export function resolveVideoSearchCaption(video) {
  const description = String(video?.description ?? '').trim()
  if (description) return description
  const title = String(video?.title ?? '').trim()
  if (title && !looksLikeAutoGeneratedTitle(title)) return title
  return 'Xem video'
}

export function emptySuggestPayload() {
  return {
    trending: [],
    users: [],
    hashtags: [],
    videos: [],
  }
}
